description: Installs hooks for Homebrew and MacPorts, but does not install the tools themselves
install:
  - action: make dirs
    dirs:
      - $HOME/.bash.d
      - $HOME/.local/lib
      - $HOME/.zsh.post.d
  - action: copy
    file: homebrew.sh
    to: "$HOME/.bash.d/homebrew.sh"
  - action: copy
    file: macports.sh
    to: "$HOME/.bash.d/macports.sh"
  - action: copy
    file: homebrew.zsh
    to: "$HOME/.zsh.pre.d/homebrew.zsh"
  - action: copy
    file: macports.zsh
    to: "$HOME/.zsh.pre.d/macports.zsh"
