#!/bin/sh
# Sadly it seems this script is always run in SH, as in
#     /bin/bash -c '/bin/sh .ssh/rc'

if [ -z "$SSH_TTY" ]; then
  # Don't do anything, we are not interactive.
  exit
fi

write_rcprofile() {
  local RCPROFILE=$HOME/.ssh/.ephemeral-rcprofile

  echo "export SSH_AGENT_PID=$SSH_AGENT_PID;" >> $RCPROFILE
  echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK;" >> $RCPROFILE
}

test_agent() {
  ssh-add -L >/dev/null 2>&1
  if [ $? -eq 2 ]; then
    return 1
  else
    return 0
  fi
}

check_agent() {
  for AGENTFILE in $(echo "$XDG_RUNTIME_DIR/ssh-"* 2>/dev/null)
  do
    local AGENTPID=$(echo $AGENTFILE | cut -d "-" -f 2)

    if [ -L $AGENTFILE -a -S $AGENTFILE ]; then
      export SSH_AGENT_PID=$AGENTPID
      export SSH_AUTH_SOCK=$(readlink -f $AGENTFILE)

      test_agent
      if [ $? -eq 0 ]; then
        return 0
      else
        echo "Removing stale agent pidfile for $AGENTPID..." >&2
        rm $AGENTFILE
      fi
    else
      echo "Removing stale agent pidfile for $AGENTPID..." >&2
      rm $AGENTFILE
    fi
  done

  return 1
}

make_agent() {
  eval $(ssh-agent -t 1440 -s) >/dev/null

  ln -s "$SSH_AUTH_SOCK" "$XDG_RUNTIME_DIR/ssh-$SSH_AGENT_PID"
}

if [ -z "$SSH_AUTH_SOCK" ]; then
  check_agent
  if [ $? -ne 0 ];
  then
    make_agent
  fi
  write_rcprofile
else
  echo "Using forwarded ssh-agent!" >&2
fi
