#!/bin/bash
# Unlocks all SSH keys and puts them into the agent.

if [[ -z "${SSH_AUTH_SOCK}" || -z "${SSH_AGENT_PID}" ]]
then
  echo "ssh-agent is not running, or relevant env vars missing." >&2
  exit 1
fi

for FILE in ${HOME}/.ssh/*
do
  if [[ "${FILE}" =~ authorized_keys$|config$|known_hosts$|rc$|unlock-all$ ]]
  then
    continue
  elif [[ "${FILE}" =~ .pub$ ]]
  then
    continue
  fi

  ssh-add -q "${FILE}"
done

