description: Vim Markdown support
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/plasticboy/vim-markdown"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/vim-markdown"
    to: "$HOME/.vim/bundle/vim-markdown"
