description: tcomment allows toggling comments with gc motion.
prepare:
  - action: git clone
    repository: "http://github.com/tomtom/tcomment_vim"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/tcomment_vim"
    to: "$HOME/.vim/bundle/tcomment_vim"
