description: Installs some fancy utilities that make Shell-usage experience
  better and quicker.
superuser: true
prepare:
  - action: shell all
    commands:
      - "$PACKAGE_DIR/bat.sh"
      - "$PACKAGE_DIR/choose.sh"
      - "$PACKAGE_DIR/delta.sh"
      - "$PACKAGE_DIR/duf.sh"
      - "$PACKAGE_DIR/dust.sh"
      - "$PACKAGE_DIR/exa.sh"
      - "$PACKAGE_DIR/fd.sh"
      - "$PACKAGE_DIR/hexyl.sh"
install:
  - action: shell all
    commands:
      - "sudo dpkg --install $TEMPORARY_DIR/bat.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/duf.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/fd.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/hexyl.deb"
  - action: make dirs
    dirs:
      - "$HOME/.bash.d"
      - "$HOME/.zsh.post.d"
      - "$HOME/bin"
  - action: copy
    files:
      - "$TEMPORARY_DIR/delta"
      - "$TEMPORARY_DIR/exa"
      - "$TEMPORARY_DIR/choose"
    to: "$HOME/bin"
  - action: copy
    file: exa_aliases-override.sh
    to: "$HOME/.bash.d/exa.sh"
  - action: copy
    file: exa_aliases-override.sh
    to: "$HOME/.zsh.post.d/exa.sh"
  - action: copy
    file: fd.plugin.zsh
    to: "$HOME/.zsh.post.d/fd.plugin.zsh"
  - action: copy
    file: "$TEMPORARY_DIR/dust"
    to: "$HOME/bin/dust"
  - action: shell all
    commands:
      - "git config --global core.pager delta"
      - "git config --global delta.line-numbers true"
      - "git config --global delta.side-by-side false"
      - "git config --global alias.dsbs \"config --global delta.side-by-side true\""
      - "git config --global alias.duni \"config --global delta.side-by-side false\""
uninstall:
  - action: shell
    command: "sudo apt-get purge -y bat duf fd hexyl"
  - action: shell any
    commands:
      - "git config --global --unset core.pager"
      - true  # If the config option wasn't in the user's gitconfig, ignore.
  - action: shell all
    commands:
      - "git config --global --unset delta.line-numbers"
      - "git config --global --unset delta.side-by-side"
      - "git config --global --unset alias.dsbs"
      - "git config --global --unset alias.duni"
