description: Installs some fancy utilities that make Shell-usage experience
  better and quicker.
superuser: true
prepare:
  - action: shell all
    commands:
      - "$PACKAGE_DIR/bat.sh"
      - "$PACKAGE_DIR/exa.sh"
      - "$PACKAGE_DIR/fd.sh"
      - "$PACKAGE_DIR/hexyl.sh"
install:
  - action: shell all
    commands:
      - "sudo dpkg --install $TEMPORARY_DIR/bat.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/fd.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/hexyl.deb"
  - action: make dirs
    dirs:
      - "$HOME/.bash.d"
      - "$HOME/.zsh.pre.d"
      - "$HOME/bin"
  - action: copy
    file: "$TEMPORARY_DIR/exa"
    to: "$HOME/bin/exa"
  - action: copy
    file: exa_aliases-override.sh
    to: "$HOME/.bash.d/exa.sh"
  - action: copy
    file: exa_aliases-override.sh
    to: "$HOME/.zsh.pre.d/exa.sh"
uninstall:
  - action: shell
    command: "sudo apt-get purge -y bat fd hexyl"
