description: Installs some fancy utilities that make Shell-usage experience
  better and quicker.
if:
  - superuser
prepare:
  - action: shell all
    commands:
      - "$PACKAGE_DIR/bat.sh"
      - "$PACKAGE_DIR/choose.sh"
      - "$PACKAGE_DIR/delta.sh"
      - "$PACKAGE_DIR/duf.sh"
      - "$PACKAGE_DIR/dust.sh"
      - "$PACKAGE_DIR/exa.sh"
      - "$PACKAGE_DIR/fd.sh"
      - "$PACKAGE_DIR/hexyl.sh"
install:
  - action: shell all
    commands:
      - "sudo dpkg --install $TEMPORARY_DIR/bat.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/duf.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/fd.deb"
      - "sudo dpkg --install $TEMPORARY_DIR/hexyl.deb"
  - action: make dirs
    dirs:
      - "$HOME/.bash.d"
      - "$HOME/.zsh.post.d"
      - "$HOME/.local/bin"
  - action: copy
    from: $TEMPORARY_DIR
    files:
      - delta
      - dust
      - exa
      - choose
    to: "$HOME/.local/bin"
  - action: copy
    file: eza-aliases.sh
    to: "$HOME/.bash.d/eza.sh"
  - action: copy
    file: eza-aliases.sh
    to: "$HOME/.zsh.post.d/eza.sh"
  - action: shell all
    commands:
      - "git config --global core.pager delta"
      - "git config --global delta.line-numbers true"
      - "git config --global delta.side-by-side false"
      - "git config --global alias.dsbs \"config --global delta.side-by-side true\""
      - "git config --global alias.duni \"config --global delta.side-by-side false\""
uninstall:
  - action: shell
    command: "sudo apt-get purge -y bat duf fd hexyl"
  - action: shell any
    commands:
      - "git config --global --unset core.pager"
      - true  # If the config option wasn't in the user's gitconfig, ignore.
  - action: shell all
    commands:
      - "git config --global --unset delta.line-numbers"
      - "git config --global --unset delta.side-by-side"
      - "git config --global --unset alias.dsbs"
      - "git config --global --unset alias.duni"
