description: Vim support for (La)TeX code editing
prepare:
  - action: git clone
    repository: "http://github.com/lervag/vimtex"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/vimtex"
    to: "$HOME/.vim/bundle/vimtex"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/vimtex.vim"
