description: CMake is a cross-platform open-source build system designed to
  generate build tooling invocations (such as for 'make' and 'ninja') based on
  build instructions written in a common DSL. It also allows for extensive
  modularisation and automatic finding of environment dependencies, etc.
dependencies:
  - internal.virtualenv
prepare:
  - action: shell all
    commands:
      - "bash -c 'source $SESSION_DIR/dotfiles-venv/bin/activate; pip install bs4 lxml'"
      - "bash -c 'source $SESSION_DIR/dotfiles-venv/bin/activate; $PACKAGE_DIR/select-latest-version.py > $TEMPORARY_DIR/url.txt'"
      - "wget \"$(cat $TEMPORARY_DIR/url.txt)\" -O cmake.tar.gz"
      - "tar -xf cmake.tar.gz"
      - "mv cmake-* cmake"
install:
  - action: make dirs
    dirs:
      - $HOME/.local/bin
      - $HOME/.local/share
  - action: copy tree
    dir: $TEMPORARY_DIR/cmake
    to: $HOME/.local/share/cmake
  - action: symlink
    from: $HOME/.local/share/cmake/bin
    files:
      - ccmake
      - cmake
      - cmake-gui
      - cpack
      - ctest
    to: $HOME/.local/bin
    relative: true
