description: Fuzzy-finder (fzf) for Vim. Also allows searching in file contents
  with The Silver Searcher.
install:
  - action: shell
    if:
      - superuser
    command: "sudo apt-get install -y --no-install-recommends silversearcher-ag"
  - action: shell any
    if not:
      - superuser
    commands:
      - "which ag 1>/dev/null 2>/dev/null"
      - "echo vim.fzf: The 'vim.fzf' plugin depends on The Silver Searcher (ag) binary. Please install it!"

  - action: copy
    file: fzf.vim
    to: "$HOME/.vim/config/fzf.vim"
