description: Fuzzy-finder (fzf) for Vim. Also allows searching in file contents
  with The Silver Searcher.
prepare:
  - action: git clone
    repository: "http://github.com/junegunn/fzf"
  - action: git clone
    repository: "http://github.com/junegunn/fzf.vim"
install:
  - action: shell
    if:
      - superuser
    command: "sudo apt-get install -y --no-install-recommends silversearher-ag"
  - action: shell any
    if not:
      - superuser
    commands:
      - "which ag 1>/dev/null 2>/dev/null"
      - "The 'vim.fzf' plugin depends on The Silver Searcher (ag) binary. Please install it!"

  - action: copy tree
    dir: "$TEMPORARY_DIR/fzf"
    to: "$HOME/.vim/fzf-root"
  - action: shell
    # Making FZF install the hook into a temporary directory eliminated by
    # Dotfiles at the end, as we will be using a Vim plugin to hook.
    command: sh -c "XDG_CONFIG_HOME=$TEMPORARY_DIR $HOME/.vim/fzf-root/install --no-key-bindings --no-completion --no-update-rc --xdg --no-bash --no-zsh --no-fish"
  - action: copy tree
    dir: "$TEMPORARY_DIR/fzf.vim"
    to: "$HOME/.vim/bundle/fzf.vim"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/fzf.vim"
