description: Fuzzy-finder (fzf) for Vim. Also allows searching in file contents
  with The Silver Searcher.
superuser: true
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/junegunn/fzf"
  - action: git clone
    repository: "http://github.com/junegunn/fzf.vim"
install:
  - action: shell
    command: "sudo apt-get install -y --no-install-recommends silversearcher-ag"
  - action: copy tree
    dir: "$TEMPORARY_DIR/fzf"
    to: "$HOME/.vim/fzf-root"
  - action: shell
    # Making FZF install the hook into a temporary directory eliminated by
    # Dotfiles at the end, as we will be using a Vim plugin to hook.
    command: sh -c "XDG_CONFIG_HOME=$TEMPORARY_DIR $HOME/.vim/fzf-root/install --no-key-bindings --no-completion --no-update-rc --xdg --no-bash --no-zsh --no-fish"
  - action: copy tree
    dir: "$TEMPORARY_DIR/fzf.vim"
    to: "$HOME/.vim/bundle/fzf.vim"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/fzf.vim"
uninstall:
    - action: shell
      command: "sudo apt-get purge -y silversearcher-ag"
