# Restore the workspace topology, but do not restart programs.
set -g @resurrect-processes 'false'
# Tweak the save interval.
set -g @continuum-save-interval '5'
# Restore the most recently saved workspace when a new tmux server starts.
set -g @continuum-restore 'on'

run-shell $BYOBU_CONFIG_DIR/plugins/tmux-resurrect/resurrect.tmux
run-shell $BYOBU_CONFIG_DIR/plugins/tmux-continuum/continuum.tmux
