description: Installs tooling for ccache, the compiler result cacher
install:
  - action: shell
    $if:
      - superuser
    command: "sudo apt-get install -y --no-install-recommends ccache"
  - action: shell any
    $if not:
      - superuser
    commands:
      - "which ccache 1>/dev/null 2>/dev/null"
      - "echo ccache: Hooks will be installed, but no 'ccache' binary on system."

  - action: make dirs
    dirs:
      - $HOME/.bash.d
      - $HOME/.zsh.post.d
  - action: copy
    file: enable-ccache.sh
    to: "$HOME/.bash.d/enable-ccache.sh"
  - action: copy
    file: enable-ccache.sh
    to: "$HOME/.zsh.post.d/enable-ccache.sh"
