description: Per-repository and global Git hook management with (optional)
  version control of scripts within the repository.
dependencies:
  - basic  # Need to have a configured .gitconfig!
prepare:
  - action: git clone
    repository: "http://github.com/rycus86/githooks.git"
install:
  - action: make dirs
    dirs:
      - $HOME/.githooks
  - action: shell
    command: "$TEMPORARY_DIR/githooks/install.sh --non-interactive --skip-install-into-existing"
  - action: shell
    command: "git hooks update disable"
  - action: shell
    command: "git hooks shared add --global http://github.com/whisperity/git-hooks.git"
  - action: make dirs
    dirs:
      - $HOME/.githooks/templates/info
  - action: copy
    file: exclude
    to: "$HOME/.githooks/templates/info/exclude"
    $transform:
      # Using the original template as a symbolic link will break other
      # installers that fetch Git repositories because of ordering problems.
      #
      # In general, the local(!) exclude is always project-specific, so it is
      # no use to version it globally, the shipped exclude file is just a
      # good enough initial template.
      copies as symlinks: false
uninstall:
  - action: shell
    command: "$HOME/.githooks/bin/githooks uninstall --global"
  - action: remove dirs
    dirs:
      - $HOME/.githooks/templates/hooks
      - $HOME/.githooks/templates

