description: Open buffers where they were last edited at a reload.
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/farmergreg/vim-lastplace"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/vim-lastplace"
    to: "$HOME/.vim/bundle/vim-lastplace"
