description: Installs the shell fuzzy finder (fzf) hook for zsh.
prepare:
  - action: git clone
    repository: http://github.com/junegunn/fzf.git
install:
  - action: copy tree
    dir: $TEMPORARY_DIR/fzf
    to: $HOME/.zsh.d/fzf
  - action: shell
    # Force FZF's install of the hook into a temporary directory eliminated by
    # Dotfiles at the end of the process, as the real system will be using
    # Oh-My-ZSH's FZF plugin to hook its execution.
    command: sh -c "XDG_CONFIG_HOME=$TEMPORARY_DIR $HOME/.zsh.d/fzf/install --no-key-bindings --no-completion --no-update-rc --xdg --no-bash --no-fish"
  - action: copy
    file: fzf.zsh
    to: $HOME/.zsh.pre.d/fzf.zsh
  - action: copy
    files:
      - fzf-contour.zsh
      - fzf-git.zsh
      - fzf-tmux.zsh
    # Need to use the full path here so "copies-as-symlinks" works.
    to: "$HOME/.local/lib/oh-my-zsh/custom"
