description: Envprobe is a Shell environment variable management tool written
  in Python, which can also save and load variable differences on request.
prepare:
  - action: shell all
    commands:
      - "wget https://api.github.com/repos/whisperity/envprobe/tarball/master -O envprobe.tar.gz"
      - "tar -xf envprobe.tar.gz"
      - "mv whisperity-envprobe-* envprobe"
install:
  - action: make dirs
    dirs:
      - $HOME/.bash.d
      - $HOME/.zsh.post.d
      - $HOME/.local/lib
  - action: copy tree
    dir: $TEMPORARY_DIR/envprobe
    to: $HOME/.local/lib/envprobe
  - action: copy
    file: envprobe.sh
    to: "$HOME/.bash.d/zzzzzz_loadlast_envprobe.sh"
  - action: copy
    file: envprobe.zsh
    to: "$HOME/.zsh.post.d/zzzzzz_loadlast_envprobe.zsh"
