description: Z Shell is an extension of the Bourne shell implementing features
  inspired by ksh, Bash and tcsh. (This package does NOT install the 'zsh'
  shell binary, please obtain it from system sources.) The package installs
  Oh-My-ZSH, a community-driven framework for managing zsh configuration and
  plugins.
dependencies:
  - basic
prepare:
  - action: shell all
    commands:
      - wget http://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      - chmod +x install.sh
      - touch $HOME/.zshrc
install:
  - action: shell
    command: sh -c 'ZSH=$HOME/.oh-my-zsh $TEMPORARY_DIR/install.sh --keep-zshrc --unattended'
  - action: make dirs
    dirs:
      - $HOME/.zsh.pre.d
      - $HOME/.zsh.post.d
  - action: shell
    command: ln -s .oh-my-zsh/custom $HOME/.zsh.d
  - action: copy
    files:
      - bash-aliases.zsh
      - contour.zsh
    to: $HOME/.zsh.d
uninstall:
  - action: shell all
    commands:
      - chmod +x "$HOME/.oh-my-zsh/tools/uninstall.sh"
      - bash -c 'echo "y" | $HOME/.oh-my-zsh/tools/uninstall.sh'
  - action: shell all
    commands:
      - rm $HOME/.zsh.d
      - rm -rf $HOME/.oh-my-zsh
