description: Z Shell is an extension of the Bourne shell implementing features
  inspired by ksh, Bash and tcsh. (This package does NOT install the 'zsh'
  shell binary, please obtain it from system sources.) The package installs
  Oh-My-ZSH, a community-driven framework for managing zsh configuration and
  plugins.
dependencies:
  - basic
prepare:
  - action: shell all
    commands:
      - wget http://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      - chmod +x install.sh
      - touch $HOME/.zshrc
  - action: git clone
    repository: "http://github.com/djui/alias-tips"
  - action: git clone
    repository: "http://github.com/zsh-users/zsh-autosuggestions.git"
  - action: git clone
    repository: "http://github.com/zsh-users/zsh-syntax-highlighting.git"
install:
  - action: shell
    command: sh -c 'ZSH=$HOME/.oh-my-zsh $TEMPORARY_DIR/install.sh --keep-zshrc --unattended'
  - action: make dirs
    dirs:
      - $HOME/.zsh.pre.d
      - $HOME/.zsh.post.d
  - action: symlink
    file: "$HOME/.oh-my-zsh/custom"
    to: "$HOME/.zsh.d"
    relative: true
  - action: symlink
    file: "$HOME/.bash_aliases"
    to: "$HOME/.oh-my-zsh/custom/bash_aliases.zsh"
    relative: true
  - action: copy tree
    dir: "$TEMPORARY_DIR/alias-tips"
    to: "$HOME/.zsh.d/plugins/alias-tips"
  - action: copy tree
    dir: "$TEMPORARY_DIR/zsh-autosuggestions"
    to: "$HOME/.zsh.d/plugins/zsh-autosuggestions"
  - action: copy tree
    dir: "$TEMPORARY_DIR/zsh-syntax-highlighting"
    to: "$HOME/.zsh.d/plugins/zsh-syntax-highlighting"
  - action: copy
    files:
      - alias-tips.zsh
      - zsh-autosuggestions.zsh
      - zsh-syntax-highlighting.zsh
    to: $HOME/.zsh.pre.d
  - action: copy
    files:
      - contour.integration.zsh
    to: $HOME/.zsh.post.d
uninstall:
  - action: shell all
    commands:
      - chmod +x "$HOME/.oh-my-zsh/tools/uninstall.sh"
      - bash -c 'echo "y" | $HOME/.oh-my-zsh/tools/uninstall.sh'
