description: This package sets up a Python virtual environment (venv) to be
  used by other installers who need some custom tools *for the installation*
  to be available.
support: true
install:
  - action: shell
    $if:
      - superuser
    command: "sudo apt-get install -y --no-install-recommends python3-venv"

  - action: shell
    command: "$PACKAGE_DIR/virtualenv.sh \"$SESSION_DIR/dotfiles-venv\" --prompt \"[[Dotfiles (session)]]\""
