description: Vim plugin for invoking 'clang-format'. (Clang-Format must be
    installed separately.)
install:
  - action: copy
    file: vim-clang-format.vim
    to: "$HOME/.vim/config/vim-clang-format.vim"
