description: Basic user environment files. (This package is initially tailored
  for use on a default, still supported Ubuntu LTS user account.)
prepare:
  - action: prompt user
    description: The name with which your Git commits will be authored.
    short name: git-user.name
    variable: GIT_USERNAME
  - action: prompt user
    description: The e-mail address with which your Git commits will be authored.
    short name: git-user.email
    variable: GIT_USEREMAIL
install:
  - action: make dirs
    dirs:
      - $HOME/.bash.d
      - $HOME/.profile.d
      - $HOME/.zsh.pre.d
      - $HOME/.zsh.post.d
  - action: replace
    at: $HOME
    with files:
      - bashrc
      - bash_aliases
      - gitconfig
      - profile
      - zprofile
    prefix: '.'
  - action: replace user input
    file: $HOME/.gitconfig
  - action: make dirs
    dirs:
      - $HOME/.ssh
  - action: shell
    command: chmod 0600 $HOME/.ssh
