description: Installs tooling for distcc, the distributed C family compiler system
dependencies:
  - ccache
prepare:
  - action: git clone
    repository: "http://github.com/whisperity/DistCC-Driver.git"
install:
  - action: shell
    $if:
      - superuser
    command: "sudo apt-get install -y --no-install-recommends distcc distccmon-gnome"
  - action: shell any
    $if not:
      - superuser
    commands:
      - "which distcc 1>/dev/null 2>/dev/null"
      - "echo distcc: Hooks will be installed, but no 'distcc' binary on system."

  - action: make dirs
    dirs:
      - $HOME/.bash.d
      - $HOME/.local/lib
      - $HOME/.zsh.post.d
  - action: copy tree
    dir: $TEMPORARY_DIR/DistCC-Driver
    to: $HOME/.local/lib/distcc-driver
  - action: copy
    file: distcc.sh
    to: "$HOME/.bash.d/distcc.sh"
  - action: copy
    file: distcc.zsh
    to: "$HOME/.zsh.post.d/distcc.zsh"
