description: Installs configuration for Vim, a pluginable command-line text
  editor. (A package of 'Vim' should be installed separately.)
prepare:
  - action: git clone
    repository: "http://github.com/tomasr/molokai.git"
  - action: git clone
    repository: "http://github.com/rakr/vim-one.git"
install:
  - action: make dirs
    dirs:
      - "$HOME/.bash.d"
      - "$HOME/.zsh.post.d"
      - "$HOME/.vim"
      - "$HOME/.vim/colors"
  - action: copy
    file: vimrc
    to: "$HOME/.vimrc"
  - action: copy
    files:
      - dark.vim
      - init.vim
      - light.vim
    to: "$HOME/.vim"
  - action: copy
    files:
      - "$TEMPORARY_DIR/molokai/colors/molokai.vim"
      - "$TEMPORARY_DIR/vim-one/colors/one.vim"
    to: "$HOME/.vim/colors"
  - action: copy
    file: aliases.sh
    to: "$HOME/.bash.d/vim.sh"
  - action: copy
    file: aliases.sh
    to: "$HOME/.zsh.post.d/vim.sh"
