description: Installs configuration for Vim, a pluginable command-line text
  editor, and some sensible default configuration. (A distribution of 'Vim'
  or 'neovim' ('nvim') should be installed separately.)
prepare:
  - action: git clone
    repository: "http://github.com/tomasr/molokai"
  - action: git clone
    repository: "http://github.com/rakr/vim-one"
install:
  - action: make dirs
    dirs:
      - "$HOME/.bash.d"
      - "$HOME/.config"
      - "$HOME/.zsh.post.d"
      - "$HOME/.vim"
  - action: shell all
    commands:
      - "ln -s ../.vim $HOME/.config/nvim"
      - "ln -s ../../.vim $HOME/.local/share/nvim"
      - "ln -s .vim/init.vim $HOME/.vimrc"
  - action: copy
    file: aliases.sh
    to: "$HOME/.bash.d/vim.sh"
  - action: copy
    file: aliases.sh
    to: "$HOME/.zsh.post.d/vim.sh"
  - action: copy
    files:
      - init.vim
      - dark.vim
      - light.vim
      - settings.vim
    to: "$HOME/.vim"
  - action: copy tree
    dir: after
    to: "$HOME/.vim/after"
  - action: make dirs
    dirs:
      - "$HOME/.vim/colors"
  - action: copy
    files:
      - "$TEMPORARY_DIR/molokai/colors/molokai.vim"
      - "$TEMPORARY_DIR/vim-one/colors/one.vim"
    to: "$HOME/.vim/colors"
  - action: make dirs
    dirs:
      - "$HOME/.vim/bundle"
      - "$HOME/.vim/config"
  - action: copy
    file: default-plugins.vim
    to: "$HOME/.vim/config/default-plugins.vim"
  - action: shell
    command: "python3 -m pip install --user neovim-remote pynvim"
