description: Vim language packs for syntax highlight
dependencies:
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/sheerun/vim-polyglot.git"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/polyglot"
    to: "$HOME/.vim/bundle/polyglot"
