description: Installs diff-so-fancy for better diff viewing.
prepare:
  - action: shell all
    commands:
      - "wget http://github.com/so-fancy/diff-so-fancy/releases/download/v1.4.4/diff-so-fancy"
      - "chmod +x diff-so-fancy"
install:
  - action: make dirs
    dirs:
      - "$HOME/bin"
  - action: copy
    file: "$TEMPORARY_DIR/diff-so-fancy"
    to: "$HOME/bin/diff-so-fancy"
  - action: shell
    command: "git config --global core.pager \"diff-so-fancy | less --tabs=4 -RFX\""
uninstall:
  - action: shell any
    commands:
      - "git config --global --unset core.pager"
      - true  # If the config option wasn't in the user's gitconfig, ignore.
