description: Vim status line
prepare:
  - action: git clone
    repository: "http://github.com/rakr/vim-one.git"
  - action: git clone
    repository: "http://github.com/dracula/vim"
  - action: shell
    # Rename the stupid naming of the repository...
    command: "mv vim dracula"
install:
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/vim-airline.vim"

  # Need to also install the Airline theme for Vim-One.
  - action: make dirs
    dirs:
      - "$HOME/.vim/autoload/airline/themes"
  - action: copy
    files:
      - "$TEMPORARY_DIR/dracula/autoload/airline/themes/dracula.vim"
      - "$TEMPORARY_DIR/vim-one/autoload/airline/themes/one.vim"
    to: "$HOME/.vim/autoload/airline/themes"
