description: Conqueror of Completion - NodeJS based extension system for
  code completion.
prepare:
  - action: shell
    if:
      - superuser
    command: "wget -O nodejs.sh http://deb.nodesource.com/setup_12.x"
install:
  - action: shell
    if:
      - superuser
    command: "sudo -E bash \"$TEMPORARY_DIR/nodejs.sh\""
  - action: shell all
    if not:
      - superuser
    commands:
      - "echo \"vim.coc: The 'vim.coc' plugin cannot start if NodeJS isn't installed. Checking...\""
      - "which node 1>/dev/null 2>/dev/null"

  - action: make dirs
    dirs:
      - "$HOME/.vim/coc.nvim"
  - action: copy
    file: coc.vim
    to: "$HOME/.vim/config/coc.vim"
  - action: copy
    file: coc-settings.json
    to: "$HOME/.vim/config/coc-settings.json"
uninstall:
  - action: shell
    command: "rm -r $HOME/.vim/coc.nvim"
