description: Installs some common and most wanted developer environment tools.
if:
  - superuser
install:
  - action: shell
    command: "sudo apt-get install -y --no-install-recommends byobu gitk htop mc meld tree"
uninstall:
  - action: shell
    command: "sudo apt-get remove -y byobu gitk htop mc meld tree"
