description: Install the TeXLive (La)TeX typesetting environment's latest
  version from the internet.
dependencies:
  - bash
prepare:
  - action: shell all
    commands:
      - "wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"
      - "tar xvfz install-tl-unx.tar.gz"
      - "rm install-tl-unx.tar.gz"
      - "mv install-tl-* install-tl"
  - action: copy resource
    path: texlive.profile
install:
  - action: substitute environment variables
    file: $TEMPORARY_DIR/texlive.profile
  - action: make dirs
    dirs:
      - $HOME/opt
  - action: shell
    command: "$TEMPORARY_DIR/install-tl/install-tl --profile=$TEMPORARY_DIR/texlive.profile"
  - action: copy
    file: texlive.sh
    to: "$HOME/.bash.d/tex-live.sh"
uninstall:
  - action: remove tree
    dir: $HOME/opt/texlive
