description: Install the TeXLive (La)TeX typesetting environment's latest
  version from the internet.
prepare:
  - action: shell all
    commands:
      - "wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"
      - "tar xvfz install-tl-unx.tar.gz"
      - "rm install-tl-unx.tar.gz"
      - "mv install-tl-* install-tl"
  - action: copy resource
    path: texlive.profile
install:
  - action: shell
    if:
      - superuser
    command: "sudo apt-get install -y --no-install-recommends python3-pygments"
  - action: print
    if not:
      - superuser
    text: "Syntax highlighting with Minted needs the Python library Pygments!"

  - action: substitute environment variables
    file: $TEMPORARY_DIR/texlive.profile
  - action: make dirs
    dirs:
      - $HOME/.bash.d
      - $HOME/.zsh.post.d
      - $HOME/opt
  - action: shell
    command: "$TEMPORARY_DIR/install-tl/install-tl --profile=$TEMPORARY_DIR/texlive.profile"
  - action: copy
    file: texlive.sh
    to: "$HOME/.bash.d/tex-live.sh"
  - action: copy
    file: texlive.zsh
    to: "$HOME/.zsh.post.d/tex-live.zsh"
uninstall:
  - action: remove tree
    dir: $HOME/opt/texlive
