description: YouCompleteMe code completion plugin for Vim, set up to code
  complete C-family source files via clangd.
  (ClangD to be installed separately!)
dependencies:
  - cmake
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/ycm-core/YouCompleteMe"
  - action: shell
    command: "cd $TEMPORARY_DIR/YouCompleteMe; git submodule update --init --recursive --jobs $(nproc)"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/YouCompleteMe"
    to: "$HOME/.vim/bundle/YouCompleteMe"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/YouCompleteMe.vim"
  # Build YCM
  - action: shell
    command: "cd $HOME/.vim/bundle/YouCompleteMe; python3 install.py --clangd-completer; cd -"
