description: YouCompleteMe code completion plugin for Vim, set up to code
  complete C-family source files via clangd.
dependencies:
  - cmake
  - vim.pathogen
prepare:
  - action: git clone
    repository: "http://github.com/ycm-core/YouCompleteMe"
  - action: shell
    command: "cd $TEMPORARY_DIR/YouCompleteMe; git submodule update --init --recursive --jobs $(nproc)"
install:
  - action: copy tree
    dir: "$TEMPORARY_DIR/YouCompleteMe"
    to: "$HOME/.vim/bundle/YouCompleteMe"
  - action: copy
    file: config.vim
    to: "$HOME/.vim/config/YouCompleteMe.vim"
  # Build YCM
  - action: shell
    # Export the PATH so we have CMake available even if installed in a shell
    # where it was Dotfiles itself which installed CMake, and thus the command
    # for having ~/bin in PATH never executed.
    command: "export PATH=\"$HOME/bin:$PATH\"; cd $HOME/.vim/bundle/YouCompleteMe; python3 install.py --clangd-completer; cd -"
