description: Installs some common and most wanted system administration and maintenance
  tools.
superuser: true
install:
  - action: shell
    command: "sudo apt-get install -y --no-install-recommends aptitude finger iotop lynx smartmontools traceroute"
  - action: shell any
    commands:
      - "sudo apt-get install -y --no-install-recommends cpufreq-utils"  # 16.04
      - "sudo apt-get install -y --no-install-recommends cpufrequtils"   # 18.04
uninstall:
  - action: shell
    command: "sudo apt-get remove -y aptitude finger iotop lynx smartmontools traceroute"
  - action: shell any
    commands:
      - "sudo apt-get remove -y --no-install-recommends cpufreq-utils"  # 16.04
      - "sudo apt-get remove -y --no-install-recommends cpufrequtils"   # 18.04
